apiVersion: v1alpha
kind: playwright
sauce:
  region: eu-central-1
  concurrency: 10
playwright:
  version: package.json
  configFile: playwright.sauce.config.ts
rootDir: ./
suites:
  - name: Chrome
    platformName: Windows 11
    screenResolution: 1440x900
    testMatch:
      - '.*\.spec\.ts$'
    params:
      browserName: chromium
      project: Chromium
  - name: Firefox
    platformName: Windows 11
    screenResolution: 1440x900
    testMatch:
      - '.*\.spec\.ts$'
    params:
      browserName: firefox
      project: Firefox
  - name: Webkit
    platformName: Windows 11
    screenResolution: 1440x900
    testMatch:
      - '.*\.spec\.ts$'
    params:
      browserName: webkit
      project: Webkit
